package com.khabaznia.bots.core.meta

final class Emoji {

    public static final String LANG_RU = "🇷🇺"
    public static final String LANG_EN = "🇬🇧"
    public static final String LANG_UK = "🇺🇦"

    public static final String REVIEW_1 = "  🥴  "
    public static final String REVIEW_2 = "  😒  "
    public static final String REVIEW_3 = "  😐  "
    public static final String REVIEW_4 = "  🙂  "
    public static final String REVIEW_5 = "  😊  "

    public static final String FINISH = "🏁"
    public static final String RESET = "🔙"

    public static final String GOLD = "🥇"
    public static final String SILVER = "🥈"
    public static final String BRONZE = "🥉"
    public static final String STRONG_HAND = "💪"
    public static final String LOG_WARNING = "‼️"
    public static final String LOG_INFO = "❕"
    public static final String LOG_DEBUG = "➖"

    public static final String REFRESH = "🔄"
    public static final String LEFT_ARROW = "⬅️"

    public static final String LEFT_DOWN = "⬇️"
    public static final String TRIANGLE_RIGHT = "▶️️"
    public static final String TRIANGLE_LEFT = "◀️"
    public static final String UP_ARROW = "⬆️"
    public static final String GEAR = "⚙️"
    public static final String TOOLS = "🛠️"
    public static final String FINGER_DOWN = "👇🏽"
    public static final String CHECKED_MARK = "✅"
    public static final String CROSS_MARK = "❌"
    public static final String CHECK = "✔️"
    public static final String STOPWATCH = "⏱️"
    public static final String ADMIN_ONE = "🎟️"
    public static final String CROWN = "👑"
    public static final String SCREAMING_FACE = "😱"
    public static final String STAR = "⭐"
    public static final String LOCATION_PIN = "📍"
    public static final String VULCANE_SALUTE = "🖖"
    public static final String THUMB_UP = "👍"
    public static final String STRUCTURE = "📃"
    public static final String NOTE = "🗒️"
    public static final String EYES = "👀"
    public static final String FINGERS = "🤙🏽"
    public static final String FIRE = "🔥"
    public static final String TEAM = "👥"
    public static final String FEEDBACK = "🫥"
    public static final String DICE = "🎲"
    public static final String WRITE = "✏️"
    public static final String REPLY = "🗯"
    public static final String USER = "🦸🏼"
    public static final String OKAY = "👌"
    public static final String TIP = "🏷"
    public static final String HAND_UP = "🙋"
    public static final String CHATTING = "💬"

    public static final String TEST_EMOJI_SET = "🛀🏿 🧘🏼 🛌🏿"
    public static final String AVOCADO = " 🥑"
    public static final String BOAT = "⛵️"
    public static final String WARNING_TRIANGLE = "⚠️"
}
