server.port: ${DEFAULT_PORT}

spring:
  datasource.driverClassName: org.postgresql.Driver
  groovy.template.check-template-location: false
  aop:
    proxy-target-class: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show_sql: false
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

logging:
  level:
    org.hibernate: error
    org.springframework: INFO
    com.khabaznia.bot: ${LOGGING_LEVEL}

env.only:
  chat.inactive.minutes: 15
  requests.per.second: 33
  requests.delay.limit.in.single.chat: 450
  expired.paths.in.days.count: 2
  clean.up.database.cron.expression: 0 0 2 * * *
  block.duplicate.requests: true
  locale:
    default: ru
    available: ru,en,uk
  bot:
    token: ${BOT_TOKEN}
    admin.chat.id: ${CHAT_ADMIN}
    logging.chat.id: ${CHAT_LOGGING}
    restricted.mode: false
    restricted.mode.users: ${RESTRICTED_USERS}
